language: node_js
node_js:
    - "4.2"
    - "stable"
script:
    - "npm run travis"
after_script:
    - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
